language: java
name: Email CI
sudo: required

install:
    - echo "install sth here"
    - sudo apt-get install wget #安装软件
## 一些基础环境、条件可在此进行
before_script:
  - echo "before script"
## 正式脚本，这里执行一些常见的linux命令
script:
  - echo "hello world"
  - pwd
  - ls -l
  - uname -a
  - gcc -v
## 脚本完成后的操作，如将服务部署远程主机
after_script:
    - echo "after script"
    - echo "my email: " $email
    - echo "ci env: " $PASSWORD
## 环境变量，注意，这是脚本内的环境变量
env:
  global: 
  PASSWORD: lyw.123
