language: android
sudo: false
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-android-support
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache: 
directories:
- "$HOME/.gradle/caches/"
- "$HOME/.gradle/wrapper/"
- "$HOME/.android/build-cache"
before_script:
- pwd
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_664d5124dd05_key -iv $encrypted_664d5124dd05_iv -in leeonkey.jks.enc -out leeonkey.jks -d
# 添加蒲公英上传脚本
- cd $TRAVIS_BUILD_DIR
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
- ls
- cd ..
before_deploy:
  - ls app/build/outputs/apk/release/
  - ls $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: GO8nIFMU302BUBSeA7/xU74aEier18q6yWwYK9TB/AF/aCaqWz5zUzPjxxFug1pJ4hJMTBE57KfhBMH4tTza8bzbdqoAOMEoDdD83e7krJTwjWyMWz5sMg0QO40D8mH/V5dvRw166gGxLoRS3AjW61MYMKPWnJWZRBS/+Ni+c1mu+h8JAuK2r3ZsXc7dfND7ZIFEXmb83bQu6kMWXqBDOchP0CODIeb9nLcDT0CYTa3uL2fBfoaANpLjBJgrjw+VbZATE2tKGruJlDlkMIkEB8dVZj4Z8elza8j11YmRG20FBcqmSRNhcOamAQ7R6DTElEbXaFCQQiDpViwacoV9vZfUqUHStLAw1F8qrFX6L9NCKbaXiLwEuNveUYvv7GgkgWltl5SbUAtWDehbEx5zQxgLCvZ4DxNbtZNpbSWHuxVFv35bUV4bhnmAOpjrvLYolzxo2KO03ikppQtC+/ccvCX4nbjOj+ZcQnT6VuXQet1Q06D4IwARAkIsw0VT+5/rADV70Ho3QjppbAe3ul+CpRC2REALNnovHCXYasks9k5Lxi5omq3z/GJ7bBYBRbk3U37dxVPapF9JM7HYDfOpD9vP8XbIEzTDdynmpOjI+FtRdi1nwi1a4SXMnS2qzncd6/o4qTov7LjF/7YPkEEgcKCN7pG/kTckbiNx0DvXBOE=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: Lyongwang/Leeon
    tags: true
# 在apk上传到GitHub后，使用蒲公英的上传脚本将apk上传到蒲公英
after_deploy:
  - set -e
  - ls $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/pgyer_upload.sh "app/build/outputs/apk/release/app-release.apk" $PGYER_API_KEY
