language: android
sudo: false
android:
  components:
  - build-tools-28.0.0
  - android-28
  - extra-android-m2repository
  - extra-android-support
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key: '0873834c42101bf44c7c09fffe9e74a694fc6d94'
  file: FILE TO UPLOAD
  skip_cleanup: true
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_664d5124dd05_key -iv $encrypted_664d5124dd05_iv
  -in leeonKey.enc -out leeonKey -d
